import type {Limit,Params,Problem,ProblemId} from '../problems/types';
export const EPS0=8.8541878128e-12;
export const K=1/(4*Math.PI*EPS0);
export type Vec={x:number;y:number;z:number};
// Finite distributions use total Q in nC; infinite lines use λ in nC/m;
// semi-infinite lines use λ in nC/m; an infinite sheet uses σ in nC/m². Distance and geometry are in meters.
export function field(id:ProblemId,p:Params):Vec {const d=p.distance,L=p.size,R=p.size/2,q=p.charge*1e-9;let x=0,y=0,z=0;switch(id){case 'bisector':x=K*q/(d*Math.sqrt(d*d+L*L/4));break;case 'axial':x=K*q/L*(1/d-1/(d+L));break;case 'infinite':x=2*K*q/d;break;case 'ring':z=K*q*d/(R*R+d*d)**1.5;break;case 'disk':{const sigma=q/(Math.PI*R*R);const h=Math.hypot(d,R);z=d===0?NaN:Math.sign(d)*sigma/(2*EPS0)*(R/h)*(R/(h+Math.abs(d)));break;}case 'semi':x=-K*q/d;y=K*q/d;break;case 'endpoint':{const h=Math.sqrt(d*d+L*L);x=K*q/(d*h);y=-K*(q/L)*(1/d-1/h);break;}case 'arc':x=-2*K*q*Math.sin(p.phi/2)/(R*R*p.phi);break;case 'sheet':z=d===0?NaN:Math.sign(d)*q/(2*EPS0);break;}return{x,y,z};}
export function magnitude(v:Vec){return Math.hypot(v.x,v.y,v.z);}
export function pretty(n:number){if(!Number.isFinite(n))return '—';return Math.abs(n)<.001&&n!==0?n.toExponential(2):n.toLocaleString('en-US',{maximumSignificantDigits:4});}
export function numerical(id:ProblemId,p:Params,n=12000):Vec {if(!Number.isFinite(n)||n<1)throw Error('Use a positive number of integration samples.');n=Math.floor(n);if((id==='disk'||id==='sheet')&&p.distance===0)return{x:0,y:0,z:NaN};const sum:Vec={x:0,y:0,z:0},q=p.charge*1e-9,d=p.distance,L=p.size,R=L/2;const add=(dq:number,x:number,y:number,z:number)=>{const r3=Math.hypot(x,y,z)**3;sum.x+=K*dq*x/r3;sum.y+=K*dq*y/r3;sum.z+=K*dq*z/r3;};
 if(id==='bisector'||id==='axial'||id==='endpoint'){for(let i=0;i<n;i++){const u=(i+.5)*L/n;if(id==='bisector')add(q/n,d,L/2-u,0);else if(id==='endpoint')add(q/n,d,-u,0);else add(q/n,L+d-u,0,0);}}
 if(id==='ring'||id==='arc'){for(let i=0;i<n;i++){const theta=id==='ring'?2*Math.PI*(i+.5)/n:-p.phi/2+p.phi*(i+.5)/n;add(q/n,-R*Math.cos(theta),-R*Math.sin(theta),id==='ring'?d:0);}}
 // Map the unbounded source coordinate to t in (-π/2, π/2), and sum the
 // underlying point-charge vector with its Jacobian. No closed-form field is used.
 if(id==='infinite'||id==='semi'){const span=id==='infinite'?Math.PI:Math.PI/2;for(let i=0;i<n;i++){const t=(i+.5)*span/n-(id==='infinite'?Math.PI/2:0),u=d*Math.tan(t),dq=q*d/(Math.cos(t)**2)*span/n;if(id==='infinite')add(dq,d,-u,0);else add(dq,-u,d,0);}}
 if(id==='disk'||id==='sheet'){const nr=Math.max(100,Math.floor(Math.sqrt(n))),nt=160;const sigma=id==='disk'?q/(Math.PI*R*R):q;for(let i=0;i<nr;i++){const t=(i+.5)/nr;const rho=id==='disk'?R*t:Math.abs(d)*Math.tan(Math.PI*t/2);const dr=id==='disk'?R/nr:Math.abs(d)*Math.PI/2/(Math.cos(Math.PI*t/2)**2)/nr;for(let j=0;j<nt;j++){const theta=2*Math.PI*(j+.5)/nt;add(sigma*rho*dr*2*Math.PI/nt,-rho*Math.cos(theta),-rho*Math.sin(theta),d);}}}return sum;}
/** One point on the limiting-case comparison plot. `actual` is a magnitude, so every
 * reference must be a magnitude too — otherwise a negative charge mirrors the reference
 * curve below the axis and the percentage readout disappears. Densities are derived from
 * the student's own geometry: a 2 nC rod 4 m long carries λ = 0.5 nC/m, not 2 nC/m, and a
 * 2 nC disk of radius 2 m carries σ = Q/(πR²), not 2 nC/m². Only the infinite-line and
 * sheet problems expose a density on their charge slider directly. */
export function sampleLimit(problem:Problem,p:Params,limit:Limit,t:number){const copy={...p},q=Math.abs(p.charge)*1e-9,R=p.size/2;let actual=0,target=0,label='';switch(limit.mode){case 'far':copy.distance=t*p.size;actual=magnitude(field(problem.id,copy));target=K*q/copy.distance**2;label=`distance / ${problem.id==='bisector'||problem.id==='axial'||problem.id==='endpoint'?'L':'2R'} = ${t.toFixed(1)}`;break;case 'infinite':if(problem.id==='bisector'||problem.id==='infinite'){const lambda=problem.id==='infinite'?p.charge:p.charge/p.size;copy.size=t*p.distance;copy.charge=lambda*copy.size;actual=magnitude(field('bisector',copy));target=2*K*Math.abs(lambda)*1e-9/p.distance;label=`L / r = ${t.toFixed(1)} · λ fixed`;}else if(problem.id==='endpoint'){const lambda=p.charge/p.size;copy.size=t*p.distance;copy.charge=lambda*copy.size;actual=magnitude(field('endpoint',copy));target=Math.SQRT2*K*Math.abs(lambda)*1e-9/p.distance;label=`L / r = ${t.toFixed(1)} · λ fixed`;}else{const sigma=problem.id==='sheet'?p.charge:p.charge/(Math.PI*R*R);copy.size=2*t*p.distance;copy.charge=sigma*Math.PI*(copy.size/2)**2;actual=magnitude(field('disk',copy));target=Math.abs(sigma)*1e-9/(2*EPS0);label=`R / z = ${t.toFixed(1)} · σ fixed`;}break;case 'center':copy.distance=R*(1-t/30);actual=magnitude(field('ring',copy));target=0;label=`z / R = ${(copy.distance/R).toFixed(2)}`;break;case 'maximum':copy.distance=R*t/10;actual=magnitude(field('ring',copy));target=K*q/(R*R)*2/(3*Math.sqrt(3));label=`z / R = ${(t/10).toFixed(2)} · peak = 1/√2`;break;case 'full':copy.phi=2*Math.PI*t/30;actual=magnitude(field('arc',copy));target=0;label=`φ / π = ${(copy.phi/Math.PI).toFixed(2)}`;break;case 'half':copy.phi=Math.PI;actual=magnitude(field('arc',copy));target=2*K*q/(Math.PI*R*R);label='φ = π · the semicircle';break;case 'scale':copy.distance=t;actual=magnitude(field(problem.id,copy));target=problem.id==='sheet'?q/(2*EPS0):Math.SQRT2*K*q/t;label=`${problem.id==='sheet'?'z':'r'} = ${t.toFixed(1)} m`;break;}return{actual,target,label};}
