'use client';
import {useId} from 'react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Input} from '@/components/ui/input';
import {MathText} from './Math';
import {preview} from '../symbolic/equivalence';
import type {Answer} from '../problems/types';
export function Choices({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:string[];label:string}){const id=useId();return <RadioGroup value={value} onValueChange={v=>onChange(String(v))} aria-label={label} className="choices">{options.map((o,i)=><label key={o} htmlFor={id+i} className={'option '+(value===o?'selected':'')}><RadioGroupItem id={id+i} value={o}/><span>{o}</span></label>)}</RadioGroup>}
export function AnswerInput({field,value,onChange,guided,error,palette=false}:{field:Answer;value:string;onChange:(s:string)=>void;guided:boolean;error?:boolean;palette?:boolean}){const id=useId();const options=[...field.options].sort((a,b)=>{const hash=(s:string)=>[...s].reduce((n,c)=>((n*31+c.charCodeAt(0))|0),7);return hash(a)-hash(b)});return <div className={'answer-field '+(error?'invalid':'')}><label className="answer-label" htmlFor={id}>{field.label}</label>{guided&&!palette?<RadioGroup value={value} onValueChange={v=>onChange(String(v))} aria-label={field.label} className="math-options">{options.map((o,i)=><label key={o} htmlFor={id+i} className={'math-option '+(value===o?'selected':'')}><RadioGroupItem id={id+i} value={o}/><MathText tex={preview(o)}/></label>)}</RadioGroup>:<><Input id={id} aria-label={field.label} aria-invalid={error} className="expression-input" value={value} onChange={e=>onChange(e.target.value)} placeholder={palette?'Drop a fact here, or type an expression':'Enter an expression…'} spellCheck={false} autoComplete="off" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onChange(e.dataTransfer.getData('text/plain'))}}/><div className="live-preview"><span className="eyebrow">Preview</span><MathText tex={value?preview(value):String.raw`\square`}/></div>{palette&&<div className="palette" aria-label={'Facts for '+field.label}>{options.map(o=><button key={o} className="fact-chip" draggable onDragStart={e=>e.dataTransfer.setData('text/plain',o)} onClick={()=>onChange(o)} title="Drag this fact into the blank, or click to use it"><MathText tex={preview(o)}/></button>)}</div>}</>}</div>}
