'use client';
import {useState} from 'react';
import {Slider} from '@/components/ui/slider';
import type {Problem,ProblemId,Params,Limit} from '../problems/types';
import {pretty,sampleLimit} from '../symbolic/physics';
export {sampleLimit};
import {MathText} from './Math';
const CHARGE={stroke:'var(--charge)',fill:'none',strokeLinecap:'round'} as const,RAIL={stroke:'var(--border)',strokeDasharray:'3 4',fill:'none'} as const;
function Observer({x,y,dx,dy,show=true}:{x:number;y:number;dx:number;dy:number;show?:boolean}){return <g><circle cx={x} cy={y} r="4" fill="var(--foreground)"/>{show&&<path d={`M${x+dx*.35} ${y+dy*.35}l${dx} ${dy}`} stroke="var(--field)" strokeWidth="2" fill="none"/>}</g>}
/** Silhouette of the geometry the plot above is actually sweeping: source in charge colour,
 *  P as a filled dot with its surviving field direction. Decorative — every number the
 *  student needs is in the plot's aria-label and the readout below. */
function LimitFigure({id,mode,t}:{id:ProblemId;mode:Limit['mode'];t:number}){
 const k=mode==='far'?Math.max(.13,1/t):mode==='infinite'?Math.min(1,t/12):1,unbounded=mode==='infinite'&&k>.92;
 if(id==='bisector'||id==='infinite'){const h=id==='infinite'?22:Math.max(3,22*k);return <><path d="M64 25H190" {...RAIL}/><path d={`M64 ${25-h}V${25+h}`} {...CHARGE} strokeWidth="7"/>{(id==='infinite'||unbounded)&&<path d="M57 6l14-4M57 44l14 4" {...CHARGE}/>}<Observer x={198} y={25} dx={26} dy={0}/></>}
 if(id==='axial'){const w=Math.max(9,120*k);return <><path d={`M${44+w} 25H196`} {...RAIL}/><path d={`M44 25h${w}`} {...CHARGE} strokeWidth="7"/><Observer x={204} y={25} dx={26} dy={0}/></>}
 if(id==='semi'){const y=32-16*Math.min(1,(t-1)/29);return <><path d="M108 38H246" {...CHARGE} strokeWidth="7"/><path d="M238 31l9 7-9 7" {...CHARGE}/><path d={`M108 38V${y+6}`} {...RAIL}/><Observer x={108} y={y} dx={-11} dy={-11}/></>}
 if(id==='endpoint'){const h=Math.max(3,26*k);return <><path d="M104 34H190" {...RAIL}/><path d={`M104 34V${34-h}`} {...CHARGE} strokeWidth="7"/>{unbounded&&<path d="M97 12l7-6 7 6" {...CHARGE}/>}<Observer x={198} y={34} dx={17} dy={8}/></>}
 if(id==='arc'){const a=mode==='full'?2*Math.PI*t/30:Math.PI,d=Array.from({length:49},(_,i)=>{const s=-a/2+a*i/48;return `${i?'L':'M'}${(152+17*Math.cos(s)).toFixed(1)},${(25-17*Math.sin(s)).toFixed(1)}`}).join(' ');return <><path d={d} {...CHARGE} strokeWidth="5"/><Observer x={152} y={25} dx={-28} dy={0} show={a<6.2}/></>}
 // Ring, disk and sheet share an axial view: the source lies in a plane, P sits above it on the axis.
 const filled=id!=='ring',plane=id==='sheet'&&mode==='scale';
 const rx=filled&&mode==='infinite'?24+98*k:Math.max(4,(filled?36:32)*k),ry=Math.max(2,(filled?10:9)*(filled&&mode==='infinite'?1:k));
 // Only the ring's centre limit drops the arrow: there the field really is zero.
 const h=mode==='center'?3+18*(1-t/30):mode==='maximum'?4+17*Math.min(1,t/30):plane?7+14*Math.min(1,(t-1)/29):21;
 return <><path d={`M130 36V${41-h}`} {...RAIL}/>{plane?<><path d="M8 36H252" {...CHARGE} strokeWidth="3"/><path d="M8 36l9-6m-9 6 9 6m235-6-9-6m9 6-9 6" {...CHARGE}/></>:<ellipse cx="130" cy="36" rx={rx} ry={ry} {...CHARGE} fill={filled?'color-mix(in srgb,var(--charge) 20%,transparent)':'none'} strokeWidth={filled?2.5:5}/>}<Observer x={130} y={36-h} dx={0} dy={-10} show={h>8}/></>
}
export function Assessment({problem,params,limit}:{problem:Problem;params:Params;limit:Limit}){const [t,setT]=useState(4);const samples=Array.from({length:70},(_,i)=>sampleLimit(problem,params,limit,1+29*i/69));const max=Math.max(...samples.flatMap(x=>[x.actual,x.target]),1e-10);const path=(key:'actual'|'target')=>samples.map((v,i)=>`${i?'L':'M'}${40+i*410/69},${164-v[key]/max*127}`).join(' ');const val=sampleLimit(problem,params,limit,t);const error=val.target>0?100*Math.abs(val.actual-val.target)/val.target:null;return <div className="assessment"><MathText tex={limit.formula} block/><div className="comparison-labels"><span><i className="legend-dot field"/>Your exact field</span><span><i className="legend-dot"/>Expected limit</span></div><svg viewBox="0 0 480 205" className="comparison-plot" role="img" aria-label={`Electric field comparison for ${limit.title}. Exact field ${pretty(val.actual)} newtons per coulomb, reference ${pretty(val.target)}.`}><path d="M40 25V165H457" stroke="var(--ghost)" fill="none"/>{[0,1,2,3].map(i=><line key={i} x1="40" x2="452" y1={37+i*42} y2={37+i*42} stroke="var(--border)" strokeDasharray="3 4"/>)}<path d={path('target')} stroke="var(--charge)" strokeWidth="2" strokeDasharray="6 4" fill="none"/><path d={path('actual')} stroke="var(--field)" strokeWidth="2.7" fill="none"/><circle cx={40+(t-1)*410/29} cy={164-val.actual/max*127} r="5" fill="var(--field)"/><text x="7" y="18">E / Eₘₐₓ</text><text x="35" y="186">1</text><text x="432" y="186">30</text><text x="143" y="199">{limit.mode==='far'?'distance / object size':limit.mode==='infinite'?'object size / distance':limit.mode==='full'?'arc angle → 2π':limit.mode==='center'?'z / R → 0 · approach the ring centre':limit.mode==='maximum'?'z / R · the peak sits at 1/√2':limit.mode==='scale'?(problem.id==='sheet'?'height z, in metres':'distance r, in metres'):'φ fixed at π · this case is a single value'}</text></svg><div className="limit-mini" aria-hidden="true"><svg viewBox="0 0 260 48"><LimitFigure id={problem.id} mode={limit.mode} t={t}/></svg></div><Slider aria-label="Explore limiting case" min={1} max={30} step={.1} value={[t]} onValueChange={v=>setT((v as number[])[0])} disabled={limit.mode==='half'}/><div className="control-label" style={{marginTop:10}}>{val.label}</div><div className="numerical-check"><span>Exact <strong>{pretty(val.actual)} N/C</strong></span><span>{limit.reference} <strong>{pretty(val.target)} N/C</strong></span>{error!==null&&<span>Difference <strong>{error.toFixed(2)}%</strong></span>}</div></div>}
