'use client';
import { useEffect, useId, useState } from 'react';
import { ArrowDown, ArrowUpRight, Check, ChevronDown, ScanLine, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { MathText } from './Math';
import { equivalent, preview, safeParse } from '../symbolic/equivalence';
import {intervalWeights} from '../diagrams/sampling';
import type { Params, Problem } from '../problems/types';
import './workbench.css';
type Mode = 'divide' | 'project' | 'sum' | 'integrate';
export type EquationWorkbenchProps = {problem:Problem;derivationProblem?:Problem;params:Params;count:number;continuum:number;progress:number;mode:Mode;onModeChange:(mode:Mode)=>void;onHighlight?:(name:string)=>void;boundRange:[number,number];onBoundRangeChange:(range:[number,number])=>void};
const raw=String.raw;
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
function fraction(n:number){for(let d=1;d<=100;d++)if(Math.abs(n*d-Math.round(n*d))<1e-7)return d===1?`${Math.round(n)}`:`${Math.round(n*d)}/${d}`;return `${Number(n.toFixed(4))}`;}
function scaled(n:number,s:string){return n===0?'0':n===1?s:n===-1?`-${s}`:`(${fraction(n)})*${s}`;}
function boundExpression(p:Problem,percent:number){const t=clamp(percent/100);if(t===0)return p.bounds[0];if(t===1)return p.bounds[1];if(p.id==='bisector'||(p.id==='infinite'&&p.variable==='y'))return scaled(t-.5,'L');if(p.id==='axial'||p.id==='endpoint')return scaled(t,'L');if(p.id==='ring')return scaled(2*t,'pi');if(p.id==='arc')return scaled(t-.5,'phi');if(p.id==='disk')return scaled(t,'R');if(p.id==='infinite')return scaled(t-.5,'pi');return `${p.id==='sheet'?'z':'r'}*tan(${scaled(t/2,'pi')})`;}
function boundPercent(p:Problem,value:string,params:Params){if(equivalent(value,p.bounds[0],p).ok)return 0;if(equivalent(value,p.bounds[1],p).ok)return 100;const x=safeParse(value).compile().evaluate({L:params.size,R:params.size/2,z:params.distance,r:params.distance,a:params.distance,pi:Math.PI,phi:params.phi,Infinity});if(typeof x!=='number'||!Number.isFinite(x))throw Error('Use a bound inside this distribution.');if(p.id==='bisector'||(p.id==='infinite'&&p.variable==='y'))return 100*(x/params.size+.5);if(p.id==='axial'||p.id==='endpoint')return 100*x/params.size;if(p.id==='ring')return 100*x/(2*Math.PI);if(p.id==='arc')return 100*(x/params.phi+.5);if(p.id==='disk')return 200*x/params.size;if(p.id==='infinite')return 100*(x/Math.PI+.5);return 200*Math.atan(x/Math.abs(params.distance))/Math.PI;}
const labels:Record<Mode,string>={divide:'One piece of charge',project:'One field contribution',sum:'Add the contributions',integrate:'The continuous field'};
export function EquationWorkbench({problem:p,derivationProblem,params,count,continuum,progress,mode,onModeChange,onHighlight,boundRange,onBoundRangeChange}:EquationWorkbenchProps){
 const uid=useId();const[focus,setFocus]=useState<string|null>(null);const[worked,setWorked]=useState(false);const[stepCount,setStepCount]=useState(1);const[boundsOpen,setBoundsOpen]=useState(false);const[bounds,setBounds]=useState<[string,string]>(p.bounds);const[feedback,setFeedback]=useState('');
 useEffect(()=>{setWorked(false);setStepCount(1);setFocus(null);setFeedback('');},[p.id,p.variable,derivationProblem?.variable]);
 useEffect(()=>{setBounds([boundExpression(p,boundRange[0]),boundExpression(p,boundRange[1])]);},[p.id,p.variable,boundRange[0],boundRange[1]]);
 const surface=p.id==='disk'||p.id==='sheet',component=['ring','disk','sheet'].includes(p.id)?'z':'x',allBounds=boundRange[0]<=.001&&boundRange[1]>=99.999,continuous=continuum>=.99;
 const complete=allBounds&&progress>=.999&&mode==='integrate'&&continuous;
 const lower=preview(boundExpression(p,boundRange[0])),upper=preview(boundExpression(p,boundRange[1])),swept=preview(boundExpression(p,boundRange[0]+(boundRange[1]-boundRange[0])*clamp(progress)));
 const limit=p.id==='infinite'&&p.variable==='y'?raw`\lim_{L\to\infty}`:'';
 const integral=raw`E_${component}=${limit}\int_{${lower}}^{${swept}}${p.kernelTex}\,d${p.variableTex}`;
 const yIntegral=p.id==='endpoint'?raw`E_y=-\int_{${lower}}^{${swept}}\frac{k\lambda y}{(y^2+r^2)^{3/2}}\,dy`:raw`E_y=\int_{${lower}}^{${swept}}\frac{k\lambda r}{(x^2+r^2)^{3/2}}\,dx`;
 const differential=p.id==='infinite'&&p.variable==='theta'?raw`dQ=\lambda r\sec^2\theta\,d\theta`:p.dqTex;
 const finiteCharge=(p.id==='infinite'?differential.replace('=','\\approx'):differential).replace(/dQ/g,raw`\Delta Q`).replace(/d([xys])/g,raw`\Delta $1`).replace(/d\\theta/g,raw`\Delta\theta`);
 const contribution=surface?raw`dE_z=\frac{kz\,dQ}{(s^2+z^2)^{3/2}}`:raw`d\mathbf E=\frac{k\,dQ}{r_i^2}\,\hat{\mathbf r}_i`;
 const finiteField=surface?raw`\Delta E_z\approx\frac{kz\,\Delta Q}{(s^2+z^2)^{3/2}}`:raw`\Delta\mathbf E_i\approx\frac{k\,\Delta Q_i}{r_i^2}\,\hat{\mathbf r}_i`;
 const m=Number(intervalWeights(count,boundRange,progress).reduce((sum,w)=>sum+Math.abs(w),0).toFixed(2));const intervalCount=Number((count*Math.abs(boundRange[1]-boundRange[0])/100).toFixed(2));
 const shown=mode==='divide'?(continuous?differential:finiteCharge):mode==='project'?(continuous?contribution:finiteField):mode==='sum'?raw`\mathbf E_{\mathrm{partial}}\approx\sum_{i=1}^{${count}}w_i\Delta\mathbf E_i`:integral;
 const algebra=derivationProblem??p;const original=algebra.steps[6]?.worked??[];
 const steps=p.id==='bisector'?[{text:'Turn the changing distance into an angle. Hold r fixed as the source position changes.',tex:raw`y=r\tan u,\quad dy=r\sec^2u\,du`},{text:'The Jacobian supplies two powers of secant. One remains in the denominator.',tex:raw`\int\frac{r\,dy}{(y^2+r^2)^{3/2}}=\frac1r\int\cos u\,du`},{text:'Integrate, then return to the original triangle.',tex:raw`\frac{\sin u}{r}=\frac{y}{r\sqrt{y^2+r^2}}`},...original.slice(1)]:original;
 const explanations:Record<string,string>={element:surface?'The highlighted piece is a whole thin ring. Its area is circumference × radial width. The ring’s own sideways contributions have already canceled.':p.id==='infinite'&&p.variable==='theta'?'The source is still a line. Changing to an angle requires dy = r sec²θ dθ; that factor changes the charge of each angular slice.':'Density gives the charge per unit length. Multiply it by the highlighted length to get the charge in this piece.',distance:'This is the distance from the selected source element to P. The source coordinate varies through the sum; the observation point stays fixed.',components:p.id==='semi'?'The source-to-P displacement is (−x, r). Both components survive: leftward and upward for positive charge.':p.id==='endpoint'?'The source-to-P displacement is (r, −y). Both components survive: rightward and downward for positive charge.':'Project each contribution before adding. A signed component can be negative; the field magnitude is always nonnegative.',symmetry:allBounds?p.symmetry.text:'A partial interval may omit matching partners. Restore the full distribution to recover its symmetry; the selected component integral still applies.'};
 function highlight(name:string){setFocus(focus===name?null:name);onHighlight?.(focus===name?'':name);}
 function applyBounds(event:React.FormEvent){event.preventDefault();try{const a=boundPercent(p,bounds[0],params),b=boundPercent(p,bounds[1],params);if(a<-.000001||b>100.000001||a>=b)throw Error('Choose an increasing interval inside the distribution.');onBoundRangeChange([Math.max(0,a),Math.min(100,b)]);onModeChange('integrate');setFeedback(a===0&&b===100?'Whole distribution selected. Equivalent forms accepted.':'Interval applied. The integral and highlighted region now match.');}catch(e){setFeedback(e instanceof Error?e.message:'Check the expressions and try again.');}}
 return <aside className="ew-panel" aria-label="Live equation workbench"><header className="ew-header"><h2>See the sum take shape.</h2></header><div className="ew-content">
 <div className="ew-equation-label"><span>{labels[mode]}</span><span>{continuous?'Continuous':`${count} pieces`}</span></div><div className={`ew-equation ew-mode-${mode}`}><MathText tex={shown} block/>{mode==='integrate'&&(p.id==='semi'||p.id==='endpoint')&&<MathText tex={yIntegral} block/>}</div>
 <p className="ew-context">{mode==='divide'?(continuous?'dQ is the differential charge: the limit of an ever smaller piece.':'Each finite piece stands in for a small region of charge. Increase the count to make the approximation finer.'):mode==='project'?(surface?'A complete annulus uses the ring’s axial field, with transverse components already canceled.':'The direction comes from the source-to-P displacement. Project this vector onto each axis.'):mode==='sum'?`${m} of ${intervalCount} equivalent pieces accumulated. A partly swept piece is weighted fractionally. The ≈ reminds us that finite pieces approximate a continuous distribution.`:progress<.999?'The upper limit follows the sweep. Every newly included slice adds its signed contribution.':allBounds?(limit?'First integrate a finite rod. Then extend L without limit while holding λ fixed.':'Every source element is included. The definite integral describes the continuous distribution exactly.'):'This integral covers the selected interval. Restore both endpoints to see the full-distribution result.'}</p>
 <div className="ew-flow" aria-label="Equation exploration modes">{(['divide','project','sum','integrate'] as Mode[]).map((v,i)=><button key={v} onClick={()=>onModeChange(v)} aria-pressed={v===mode}><span>{['ΔQ','dE','Σ','∫'][i]}</span><small>{['Divide','Project','Sum','Integrate'][i]}</small></button>)}</div>
 <div className="ew-building-blocks"><div className="ew-section-title"><span>Inside the equation</span><span>Tap to connect</span></div>{[{id:'element',label:surface?'Charge in a thin ring':'Charge in one piece',tex:differential},{id:'distance',label:'Distance to P',tex:raw`r_i=${preview(p.distance)}`},{id:'components',label:'Signed projection',tex:raw`dE_${component}=${p.kernelTex}\,d${p.variableTex}`},{id:'symmetry',label:'Which directions survive?',tex:allBounds?p.symmetry.tex:raw`\text{Check partners in this interval}`}].map(item=><div className="ew-concept" key={item.id}><button className={focus===item.id?'is-active':''} onClick={()=>highlight(item.id)} aria-expanded={focus===item.id} aria-controls={`${uid}-${item.id}`}><span className={`ew-dot ew-dot-${item.id}`}/><span><small>{item.label}</small><MathText tex={item.tex}/></span><ChevronDown size={14}/></button>{focus===item.id&&<div className="ew-concept-detail" id={`${uid}-${item.id}`}><p>{explanations[item.id]}</p>{item.id==='components'&&p.id==='semi'&&<MathText tex={raw`dE_y=\frac{k\lambda r\,dx}{(x^2+r^2)^{3/2}}`} block/>}</div>}</div>)}</div>
 <div className="ew-bounds"><button className="ew-disclosure" onClick={()=>setBoundsOpen(!boundsOpen)} aria-expanded={boundsOpen} aria-controls={`${uid}-bounds`}><span><ScanLine size={15}/>Integration interval</span><span><MathText tex={raw`${lower}\;\to\;${upper}`}/><ChevronDown size={14}/></span></button>{boundsOpen&&<form id={`${uid}-bounds`} className="ew-bound-form" onSubmit={applyBounds}><p>Use symbols such as <MathText tex={p.boundTex[0]}/> and <MathText tex={p.boundTex[1]}/>. Equivalent expressions work, too.</p><div className="ew-bound-fields"><label htmlFor={`${uid}-lower`}>Lower bound<input id={`${uid}-lower`} value={bounds[0]} onChange={e=>setBounds([e.target.value,bounds[1]])} autoComplete="off" spellCheck={false}/></label><label htmlFor={`${uid}-upper`}>Upper bound<input id={`${uid}-upper`} value={bounds[1]} onChange={e=>setBounds([bounds[0],e.target.value])} autoComplete="off" spellCheck={false}/></label></div><div className="ew-bound-actions"><Button type="submit" size="sm">Apply interval</Button><Button type="button" variant="ghost" size="sm" onClick={()=>{setBounds(p.bounds);onBoundRangeChange([0,100]);setFeedback('Whole distribution selected.');}}>Whole distribution</Button></div>{feedback&&<p className="ew-bound-feedback" role="status">{feedback}</p>}</form>}</div>
 {complete&&<div className="ew-result"><span className="ew-result-label">The whole distribution</span><MathText tex={p.resultTex} block/>{p.secondaryResultTex&&<MathText tex={p.secondaryResultTex} block/>}<p>Signed field component{['semi','endpoint'].includes(p.id)?'s':''}. Reversing the charge reverses the field.</p></div>}
 <div className="ew-worked"><button className="ew-disclosure" onClick={()=>setWorked(!worked)} aria-expanded={worked} aria-controls={`${uid}-worked`}><span><Sparkles size={15}/>Unfold the integration</span><ChevronDown size={15}/></button>{worked&&<div id={`${uid}-worked`} className="ew-worked-body"><p className="ew-context">{algebra.id==='infinite'&&algebra.variable==='y'?'Alternate derivation: start with a finite rod of length L, then let L grow at fixed λ. The live model above remains the infinite line.':allBounds?'Follow the algebra for the whole distribution, one transformation at a time.':'These steps derive the whole-distribution result. Your selected partial interval remains above.'}</p>{steps.slice(0,stepCount).map((step,i)=><div className="ew-worked-step" key={`${p.id}-${p.variable}-${i}`}><span>{String(i+1).padStart(2,'0')}</span><div><p>{step.text}</p><MathText tex={step.tex} block/></div></div>)}{stepCount<steps.length?<Button className="ew-next-step" variant="outline" onClick={()=>setStepCount(stepCount+1)}>Next transformation<ArrowDown size={14}/></Button>:<p className="ew-worked-done"><Check size={13}/>Every transformation accounted for.</p>}</div>}</div>
 <footer className="ew-footer"><MathText tex={p.densityTex}/><MathText tex={raw`k=\frac1{4\pi\varepsilon_0}`}/></footer><details className="ew-references"><summary>Model assumptions & references</summary><p>{p.setup}</p><p>Geometry uses meters. Finite distributions use total charge; unbounded distributions hold charge density fixed.</p>{p.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={12}/></a>)}</details>
 </div></aside>;
}
