import {Check} from 'lucide-react';
import {MathText} from './Math';
import {stageOf,type Problem,type StepKind} from '../problems/types';
import type {LessonState} from '../state/progress';
/** The integral as far as the reader has got: each stage reached adds its factor. Nothing is
 * scored; the panel only shows how much of the expression the steps so far account for. */
export function IntegralPanel({problem:p,lesson:l}:{problem:Problem;lesson:LessonState}){const reached=(k:StepKind)=>{const i=stageOf(p,k);return i>=0&&i<=l.stage;},scalar=p.quantity==='V',n=p.steps.length;
 const tex=reached('integrate')?p.resultTex:reached('bounds')?p.integralTex:reached('variable')?String.raw`${scalar?'V':'E'}=\int ${p.kernelTex}\,d${p.variableTex}`:reached('symmetry')?p.symmetry.tex:reached('contribution')?scalar?String.raw`dV=\frac{k\,dQ}{r_i}`:String.raw`dE=\frac{k\,dQ}{r_i^2}`:reached('element')?p.dqTex:scalar?String.raw`V(P)=\int dV`:String.raw`\mathbf E(P)=\int d\mathbf E`;
 const rows=([{k:'element',label:'Charge element',tex:p.dqTex},{k:'contribution',label:'One contribution',tex:scalar?String.raw`dV=k\,dQ/r_i`:String.raw`dE=k\,dQ/r_i^2`},{k:'symmetry',label:'Symmetry',tex:p.symmetry.tex},{k:'variable',label:'One variable',tex:p.kernelTex},{k:'bounds',label:'Integration bounds',tex:String.raw`${p.variableTex}:\ ${p.boundTex[0]}\to ${p.boundTex[1]}`}] as {k:StepKind;label:string;tex:string}[]).filter(row=>stageOf(p,row.k)>=0);
 return <aside className="panel equation-panel" aria-label="The integral so far"><div className="panel-head"><span>The derivation</span><span className="pill">Step {Math.min(l.stage,n-1)+1} of {n}</span></div><div className="equation-body"><div className="eyebrow muted">{reached('integrate')?'The result':'The integral so far'}</div><div className="equation-display"><MathText tex={tex} block/></div>{p.secondaryResultTex&&reached('integrate')&&<MathText tex={p.secondaryResultTex} block/>}<div className="math-row"><span className="muted">Density</span><MathText tex={p.densityTex}/></div><div className="math-row"><span className="muted">Observation</span><MathText tex={p.coordinate}/></div>{rows.map((row,i)=><div className={'construction-row '+(reached(row.k)?'complete':'')} key={row.k}><span className="construction-status">{reached(row.k)?<Check size={13}/>:i+1}</span><div><span className="muted">{row.label}</span><MathText tex={row.tex}/></div></div>)}</div></aside>;
}
