import {Check,LockKeyhole} from 'lucide-react';
import {MathText} from './Math';
import {Progress} from '@/components/ui/progress';
import {stageOf,type Problem,type StepKind} from '../problems/types';
import type {LessonState} from '../state/progress';
import {mastery,points} from '../state/progress';
const pts=(n:number)=>String(Number(n.toFixed(1)));
export function IntegralPanel({problem:p,lesson:l}:{problem:Problem;lesson:LessonState}){const done=(k:StepKind)=>{const i=stageOf(p,k);return i>=0&&l.completed.includes(i);},scalar=p.quantity==='V',n=p.steps.length,s=points(n);
 const tex=done('integrate')?p.resultTex:done('bounds')?p.integralTex:done('variable')?String.raw`${scalar?'V':'E'}=\int ${p.kernelTex}\,d${p.variableTex}`:done('symmetry')?p.symmetry.tex:done('contribution')?scalar?String.raw`dV=\frac{k\,dQ}{r_i}`:String.raw`dE=\frac{k\,dQ}{r_i^2}`:done('element')?p.dqTex:scalar?String.raw`V(P)=\int dV`:String.raw`\mathbf E(P)=\int d\mathbf E`;
 const rows=([{k:'element',label:'Charge element',tex:p.dqTex},{k:'contribution',label:'One contribution',tex:scalar?String.raw`dV=k\,dQ/r_i`:String.raw`dE=k\,dQ/r_i^2`},{k:'symmetry',label:'Symmetry',tex:p.symmetry.tex},{k:'variable',label:'One variable',tex:p.kernelTex},{k:'bounds',label:'Integration bounds',tex:String.raw`${p.variableTex}:\ ${p.boundTex[0]}\to ${p.boundTex[1]}`}] as {k:StepKind;label:string;tex:string}[]).filter(row=>stageOf(p,row.k)>=0);
 return <aside className="panel equation-panel" aria-label="Integral under construction"><div className="panel-head"><span>Your derivation</span><span className="pill">{l.completed.length} / {n}</span></div><div className="equation-body"><div className="eyebrow muted">{done('integrate')?'Your result':'Integral under construction'}</div><div className="equation-display"><MathText tex={tex} block/></div>{p.secondaryResultTex&&done('integrate')&&<MathText tex={p.secondaryResultTex} block/>}<div className="math-row"><span className="muted">Density</span><MathText tex={p.densityTex}/></div><div className="math-row"><span className="muted">Observation</span><MathText tex={p.coordinate}/></div>{rows.map(row=><div className={'construction-row '+(done(row.k)?'complete':'')} key={row.k}><span className="construction-status">{done(row.k)?<Check size={13}/>:<LockKeyhole size={12}/>}</span><div><span>{row.label}</span>{done(row.k)&&<MathText tex={row.tex} block/>}</div></div>)}<div className="note" style={{marginTop:20}}>{done('integrate')?scalar?'The potential is a signed scalar. Reverse the charge sign to reverse its sign; there is no direction to keep track of.':'These formulas give signed components. Reverse the charge sign to reverse the field; a field magnitude is always nonnegative.':'Each correct step adds another piece. The same structure works for every distribution.'}</div><div style={{marginTop:25}}><div className="progress-caption"><span>Mastery earned</span><strong>{mastery(l,n)} / 100</strong></div><Progress value={mastery(l,n)} aria-label="Mastery score"/><p className="score-note">Independent step: {pts(s.full)} · with a hint: {pts(s.hinted)} · revealed: {pts(s.assisted)}</p></div><div className="constant"><MathText tex={String.raw`k=\frac{1}{4\pi\varepsilon_0}`}/><span>All geometry in meters</span></div></div></aside>}
