'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, MoveHorizontal, Plus, Scissors } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { MathText } from './Math';
import './workbench.css';
const pages=[{eyebrow:'01 / MOVE & NOTICE',title:'Physics you can put your hands on.',description:'Drag the observation point P. Change the charge and its geometry. The field and equation respond together.',hint:'Try moving P. The field weakens as you move away.',icon:MoveHorizontal},{eyebrow:'02 / MAKE THE PIECES SMALLER',title:'An integral starts with one piece.',description:'Split the charge into small pieces, then keep refining. Each ΔQ shrinks as the count grows. In the continuous limit, it becomes dQ.',hint:'Try refining the rod. More pieces, less charge in each.',icon:Scissors},{eyebrow:'03 / BUILD YOUR INTUITION',title:'One arrow. A sum. The whole field.',description:'Project each tiny field, add the contributions, and watch the sum become an integral. Tap any equation ingredient to connect it to the picture.',hint:'Try sweeping through the charge. Watch the contributions add.',icon:Plus}];
export function Onboarding({open,onClose,onExplore}:{open:boolean;onClose:()=>void;onExplore?:()=>void}){
 const[page,setPage]=useState(0),[distance,setDistance]=useState(45),[refinement,setRefinement]=useState(15),[sweep,setSweep]=useState(65);
 useEffect(()=>{if(open)setPage(0);},[open]);const content=pages[page],Icon=content.icon,slices=Math.round(4+refinement*.56),px=178+distance*1.28,fieldLength=8500/(px-82);
 return <Dialog open={open} onOpenChange={value=>{if(!value)onClose();}}><DialogContent className="fb-onboarding"><div className="ob-kicker"><span className="ob-brand">∫</span>FIELD BUILDER<span className="ob-welcome">A quick introduction</span></div>
 <div className="ob-visual"><svg viewBox="0 0 480 205" role="img" aria-label={content.hint}><defs><marker id="onboard-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="var(--field)"/></marker><pattern id="onboard-grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".75" fill="var(--grid)"/></pattern></defs><rect width="480" height="205" fill="url(#onboard-grid)"/>
 {page===0&&<><path d="M82 35V168" stroke="var(--charge)" strokeWidth="8" strokeLinecap="round"/>{[50,75,100,125,150].map(y=><g key={y}><text x="61" y={y+4} className="ob-plus">+</text><path d={`M87 ${y} L${px} 102`} stroke="var(--contribution)" strokeDasharray="3 5" opacity=".38"/></g>)}<path d={`M${px} 102h${fieldLength}`} stroke="var(--field)" strokeWidth="3" markerEnd="url(#onboard-arrow)"/><circle cx={px} cy="102" r="8" fill="var(--card)" stroke="var(--field)" strokeWidth="3"/><circle cx={px} cy="102" r="17" fill="none" stroke="var(--field)" opacity=".15"/><text x={px-5} y="76" className="ob-math">P</text><text x={px+fieldLength-8} y="86" className="ob-math">E</text><path d={`M82 185H${px}`} stroke="var(--ghost)"/><text x={(82+px)/2} y="178" className="ob-math">r</text></>}
 {page===1&&<><text x="45" y="57" className="ob-label">SAME TOTAL CHARGE</text>{Array.from({length:slices},(_,i)=><rect key={i} x={45+i*390/slices} y="84" width={Math.max(1,390/slices-Math.max(.7,2.8-refinement/40))} height="33" rx={refinement>60?1:3} fill={i===Math.floor(slices*.55)?'var(--charge)':'var(--charge-fill)'} stroke="var(--charge)" strokeOpacity=".75" strokeWidth=".7"/>)}<path d={`M${45+(Math.floor(slices*.55)+.5)*390/slices} 124v18`} stroke="var(--charge)"/><text x={45+(Math.floor(slices*.55)+.5)*390/slices} y="164" textAnchor="middle" className="ob-math">ΔQ</text><text x="45" y="189" className="ob-label">{slices} PIECES</text><text x="435" y="189" textAnchor="end" className="ob-label">{refinement>90?'APPROACHING THE LIMIT':'ΔQ = Q / N'}</text></>}
 {page===2&&<>{Array.from({length:12},(_,i)=><g key={i} opacity={i<Math.round(sweep*.12)?1:.15}><rect x={45+i*13} y="43" width="9" height="24" rx="2" fill="var(--charge)"/><path d={`M${49+i*13} 78L265 125`} stroke="var(--contribution)" opacity=".45"/><path d={`M${65+i*10} 164l10 -3`} stroke="var(--field)" strokeWidth="2.5"/></g>)}<circle cx="265" cy="125" r="6" fill="var(--card)" stroke="var(--field)" strokeWidth="2"/><text x="260" y="106" className="ob-math">P</text><path d={`M265 125h${1+sweep*1.18}`} stroke="var(--field)" strokeWidth="3.5" markerEnd="url(#onboard-arrow)"/><text x="45" y="189" className="ob-label">SMALL CONTRIBUTIONS</text><text x="320" y="157" className="ob-label">THEIR VECTOR SUM</text></>}
 </svg><div className="ob-mini-control"><Icon size={15}/><Slider aria-label={page===0?'Preview observation-point distance':page===1?'Preview number of charge pieces':'Preview accumulated contributions'} min={0} max={100} value={[page===0?distance:page===1?refinement:sweep]} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;if(page===0)setDistance(n);else if(page===1)setRefinement(n);else setSweep(n);}}/><span>{page===0?'Move P':page===1?'Refine':'Add up'}</span></div></div>
 <div className="ob-copy" key={page}><span className="ew-eyebrow">{content.eyebrow}</span><DialogTitle className="ob-title">{content.title}</DialogTitle><DialogDescription className="ob-description">{content.description}</DialogDescription><div className="ob-formula"><MathText tex={page===0?String.raw`\text{geometry}\ \longrightarrow\ \mathbf E(P)`:page===1?String.raw`N\to\infty\qquad\Delta Q\to dQ`:String.raw`\mathbf E\approx\sum_i\Delta\mathbf E_i\quad\longrightarrow\quad\mathbf E=\int d\mathbf E`}/></div><p className="ob-hint">{content.hint}</p></div>
 <div className="ob-footer"><div className="ob-dots" aria-label="Introduction pages">{pages.map((p,index)=><button key={p.eyebrow} className={index===page?'active':''} onClick={()=>setPage(index)} aria-label={`Introduction page ${index+1}`} aria-current={index===page?'step':undefined}/>)}</div><div className="ob-actions">{page>0?<Button variant="ghost" onClick={()=>setPage(page-1)} aria-label="Previous introduction page"><ArrowLeft size={16}/></Button>:<Button variant="ghost" onClick={onClose}>Skip intro</Button>}<Button onClick={()=>{if(page===2){onExplore?.();onClose();}else setPage(page+1);}}>{page===2?'Start exploring':'Continue'}<ArrowRight size={15}/></Button></div></div>
 </DialogContent></Dialog>;
}
