import type {Problem,Answer} from './types';
import {axial,ring,disk,semi,arc,sheet,endpoint,infiniteFrom} from './more';
const raw=String.raw;
export const SOURCE={title:'OpenStax · University Physics 2, §5.5',url:'https://openstax.org/books/university-physics-volume-2/pages/5-5-calculating-electric-fields-of-charge-distributions'};
const f=(id:string,label:string,expected:string,tex:string,options:string[],hint:string,mistakes:Answer['mistakes']=[]):Answer=>({id,label,expected,tex,options,hint,mistakes});
export const bisector:Problem={
 id:'bisector',number:'01',title:'A line of charge',short:'Finite line',subtitle:'Build the electric field on the perpendicular bisector of a uniform rod.',kind:'Uniform rod',
 setup:'A thin rod of length L carries uniform positive charge Q. It lies on the y-axis, centered at the origin. Find the electric field at P = (r, 0), with r > 0.',origin:'At the center of the rod',alternateOrigin:'At the lower end',coordinate:'P=(r,0)',variable:'y',variableTex:'y',density:'Q/L',densityTex:raw`\lambda=\frac{Q}{L}`,dq:'lambda*dy',dqTex:raw`dQ=\lambda\,dy`,distance:'sqrt(y^2+r^2)',projection:'r/sqrt(y^2+r^2)',kernel:'k*lambda*r/(y^2+r^2)^(3/2)',kernelTex:raw`\frac{k\lambda r}{(y^2+r^2)^{3/2}}`,integralTex:raw`E_x=k\lambda\int_{-L/2}^{L/2}\frac{r\,dy}{(y^2+r^2)^{3/2}}`,result:'k*Q/(r*sqrt(r^2+(L/2)^2))',resultTex:raw`E_x=\frac{kQ}{r\sqrt{r^2+(L/2)^2}}`,bounds:['-L/2','L/2'],boundTex:['-L/2','L/2'],
 symmetry:{answer:'The y-components cancel',options:['The x-components cancel','The y-components cancel','Both components cancel','Neither component cancels'],axis:'Across the x-axis',axes:['Across the x-axis','Across the y-axis','No partner exists'],text:'Pair an element at +y with an equal element at −y. Their vertical fields oppose; their horizontal fields both point toward +x. Moving the coordinate origin does not destroy this physical symmetry.',tex:raw`dE_y(y)+dE_y(-y)=0,\quad E_y=0`},
 steps:[
 {title:'Give the problem a frame of reference',text:'Choose an origin that makes the symmetry easy to see. Drag P along the x-axis to explore the distance.',hint:'The origin can go anywhere. A centered origin makes the bounds symmetric: −L/2 to +L/2. For this derivation, use that simpler choice.'},
 {title:'Start with one small piece',text:'Scrub from a few chunks to a continuous rod. What is the length of one element, and how much charge does it carry?',hint:'Linear density is charge per length. Multiply λ (C/m) by a tiny length dy (m) to get dQ (C).',fields:[f('element','Length element','dy','dy',['dy','y*dy','L*dy'],'The element is a length along the y-axis. y locates it; dy measures its width.'),f('dq','Charge element dQ','lambda*dy',raw`\lambda\,dy`,['lambda*dy','Q*dy','lambda*y*dy'],'Use charge per length times a tiny length.',[{expression:'Q*dy',message:'Q is the entire rod’s charge. Divide by L first; the orange slice only contains λ dy.',highlight:'element'}])]},
 {title:'A tiny charge makes a tiny field',text:'Use Coulomb’s law and project the field onto the axes. α is the angle of the contribution below +x for the selected upper element.',hint:'The x-component lies adjacent to α. The vertical component points down for y > 0, so it carries a minus sign.',fields:[f('field','Magnitude dE','k*dQ/ri^2',raw`\frac{k\,dQ}{r_i^2}`,['k*dQ/ri^2','k*dQ/ri','k*Q/ri^2'],'Coulomb’s field falls as distance squared.',[{expression:'k*dQ/ri',message:'That is the distance dependence of potential. The green field arrow follows the inverse-square law.',highlight:'distance'}]),f('component','x-component dEₓ','dE*cos(alpha)',raw`dE\cos\alpha`,['dE*cos(alpha)','dE*sin(alpha)','dE'],'Project onto x: adjacent / hypotenuse.',[{expression:'dE',message:'The slanted vector is longer than its horizontal component. Include cos α.',highlight:'components'}]),f('component2','y-component dEᵧ','-dE*sin(alpha)',raw`-dE\sin\alpha`,['-dE*sin(alpha)','dE*sin(alpha)','0'],'The upper element pushes a positive test charge downward.')]},
 {title:'Let symmetry do some work',text:'Compare the highlighted element with its ghost partner. Which components disappear, and which reflection pairs them?',hint:'At P, the two vertical arrows have equal lengths and opposite directions. The horizontal arrows point the same way.'},
 {title:'Make y the only changing variable',text:'Use the right triangle to replace the distance and projection. Then assemble the integrand (without dy).',hint:'r is fixed; y varies along the rod. The extra projection factor changes the denominator power from 1 to 3/2.',fields:[f('distance','Element-to-P distance rᵢ','sqrt(y^2+r^2)',raw`\sqrt{y^2+r^2}`,['sqrt(y^2+r^2)','r','y+r'],'Use the dotted right triangle.',[{expression:'r',message:'r is only the horizontal leg. The slanted distance changes as the orange slice moves up the rod.',highlight:'distance'}]),f('projection','Projection cos α','r/sqrt(y^2+r^2)',raw`\frac{r}{\sqrt{y^2+r^2}}`,['r/sqrt(y^2+r^2)','y/sqrt(y^2+r^2)','1'],'The adjacent side is r.'),f('kernel','Integrand dEₓ/dy','k*lambda*r/(y^2+r^2)^(3/2)',raw`\frac{k\lambda r}{(y^2+r^2)^{3/2}}`,['k*lambda*r/(y^2+r^2)^(3/2)','k*lambda/(y^2+r^2)','k*lambda*y/(y^2+r^2)^(3/2)'],'Multiply Coulomb’s field by cos α and substitute dQ = λ dy.')]},
 {title:'Cover the whole rod, exactly once',text:'Drag the two brackets to the rod’s ends, or enter the symbolic limits. The variable is y.',hint:'The rod has total length L, so each end is only L/2 from its center.'},
 {title:'Add every contribution',text:'Integrate your expression for Eₓ. Try the result yourself, or unfold the worked derivation.',hint:'An antiderivative of r/(y²+r²)^(3/2) is y/[r√(y²+r²)]. Remember λL = Q.',fields:[f('result','Total x-component Eₓ','k*Q/(r*sqrt(r^2+(L/2)^2))',raw`\frac{kQ}{r\sqrt{r^2+(L/2)^2}}`,['k*Q/(r*sqrt(r^2+(L/2)^2))','k*Q/r^2','2*k*Q/(r*sqrt(r^2+L^2))'],'Evaluate the antiderivative at both ends. The magnitude for either charge sign uses |Q|.')],worked:[{text:'Treat r as constant. Use the standard antiderivative (or y = r tan u).',tex:raw`\int\frac{r\,dy}{(y^2+r^2)^{3/2}}=\frac{y}{r\sqrt{y^2+r^2}}`},{text:'Evaluate at both endpoints. They contribute equally.',tex:raw`E_x=k\lambda\left[\frac{y}{r\sqrt{y^2+r^2}}\right]_{-L/2}^{L/2}=\frac{k\lambda L}{r\sqrt{r^2+(L/2)^2}}`},{text:'Use Q = λL. This is the signed x-component; the magnitude uses |Q|.',tex:raw`E_x=\frac{kQ}{r\sqrt{r^2+(L/2)^2}},\quad |\mathbf E|=\frac{k|Q|}{r\sqrt{r^2+(L/2)^2}}`}]},
 {title:'Does the physics make sense?',text:'A formula earns our trust when it behaves correctly at the extremes. Make a prediction, then explore the comparison.',hint:'Far away, the rod’s length becomes negligible relative to your distance.'}
 ],limits:[{id:'far',title:'Far away, a rod becomes a point',prompt:'When r ≫ L, which expression should the field approach?',answer:'kQ/r²',choices:['kQ/r²','2kλ/r','0 at every distance'],explanation:'From far away, the rod’s internal structure is too small to resolve. With Q fixed, the field approaches that of a point charge.',formula:raw`r\gg L:\quad E_x\longrightarrow\frac{kQ}{r^2}`,mode:'far',reference:'Point charge'},{id:'infinite',title:'Let the rod extend without end',prompt:'Hold λ fixed and let L → ∞. What happens?',answer:'E → 2kλ/r',choices:['E → 2kλ/r','E → kQ/r² with Q fixed','E → 0'],explanation:'Charge density stays fixed, so total charge grows with L. Dividing the exact result by L reveals 2kλ/r.',formula:raw`L\to\infty\; (\lambda\text{ fixed}):\quad E_x\to\frac{2k\lambda}{r}`,mode:'infinite',reference:'Infinite line'}],sources:[SOURCE],link:{id:'infinite',text:'Take this rod to infinity'}
};
export const PROBLEMS:Problem[]=[bisector,axial,infiniteFrom(bisector),ring,disk,semi,arc,sheet,endpoint];
export function getProblem(id:string,path='angular'):Problem{return id==='infinite'?infiniteFrom(bisector,path):PROBLEMS.find(p=>p.id===id)??bisector;}
