'use client';
import {useRef,type PointerEvent} from 'react';
import type {Problem,Params} from '../problems/types';
import {field,magnitude,pretty} from '../symbolic/physics';
export function Arrow({x1,y1,x2,y2,color='var(--field)',dashed=false,width=2}:{x1:number;y1:number;x2:number;y2:number;color?:string;dashed?:boolean;width?:number}){const a=Math.atan2(y2-y1,x2-x1),s=6;return <g opacity={dashed?.5:1}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth={width} strokeDasharray={dashed?'5 5':undefined}/><path d={`M${x2-s*Math.cos(a-.5)} ${y2-s*Math.sin(a-.5)}L${x2} ${y2}L${x2-s*Math.cos(a+.5)} ${y2-s*Math.sin(a+.5)}`} fill="none" stroke={color} strokeWidth={width}/></g>}
export type DiagramProps={problem:Problem;params:Params;setParams:(p:Partial<Params>)=>void;stage:number;alternate:boolean;highlight:string;boundRange:[number,number];setBoundRange:(r:[number,number])=>void};
export function Geometry({problem,params:p,setParams,stage,alternate,highlight,boundRange,setBoundRange}:DiagramProps){const ref=useRef<SVGSVGElement>(null);const drag=useRef<string|null>(null);const O={x:210,y:223},length=230,top=O.y-length/2,bottom=O.y+length/2,px=O.x+55+p.distance*35,ey=O.y-(.1+p.element*.85)*length/2;const e=field(problem.id,p),gain=Math.min(24,100/Math.max(magnitude(e),.001)),netLength=e.x*gain;const n=Math.min(120,Math.round(p.slices+(120-p.slices)*p.continuum)),ri=Math.hypot(p.distance,(.1+p.element*.85)*p.size/2);const contribution=stage>=2;const ghost=stage>=3;const bpos=(t:number)=>bottom-t/100*length;
 function point(ev:PointerEvent){const r=ref.current!.getBoundingClientRect();return{x:(ev.clientX-r.left)*660/r.width,y:(ev.clientY-r.top)*390/r.height};}
 function start(ev:PointerEvent,what:string){ev.currentTarget.setPointerCapture(ev.pointerId);drag.current=what;}
 function move(ev:PointerEvent){if(!drag.current)return;const c=point(ev);if(drag.current==='P')setParams({distance:Math.round(Math.max(.5,Math.min(6,(c.x-O.x-55)/35))*20)/20});if(drag.current==='element')setParams({element:Math.max(0,Math.min(1,((O.y-c.y)/(length/2)-.1)/.85))});if(drag.current.startsWith('bound')){const idx=Number(drag.current.slice(-1)),val=Math.max(0,Math.min(100,Math.round((bottom-c.y)/length*20)*5));const b:[number,number]=[...boundRange];b[idx]=val;setBoundRange(b);}}
 const handleProps=(what:string)=>({onPointerDown:(ev:PointerEvent<SVGGElement>)=>start(ev,what),onPointerMove:move,onPointerUp:()=>{drag.current=null},onPointerCancel:()=>{drag.current=null}});
 return <div className={'diagram highlight-'+highlight}><svg ref={ref} viewBox="0 0 660 390" role="img" aria-label="Positive rod on the y-axis. An upper charge element points diagonally toward P. Its vertical field cancels with the lower partner."><path d={`M75 ${O.y}H605M${O.x} 355V38`} fill="none" stroke="var(--ghost)"/><text x="610" y={O.y+6}>x</text><text x={O.x-7} y="26">{alternate?'y′':'y'}</text><path d={`M${O.x} ${ey}H${px}V${O.y}`} className="construction" stroke="var(--ghost)" strokeDasharray="4 5" fill="none" opacity=".5"/><line x1={O.x} y1={ey} x2={px} y2={O.y} className="distance-mark" stroke="var(--contribution)" strokeDasharray="5 5" strokeWidth="1.5"/><text x={(O.x+px)/2+5} y={(ey+O.y)/2-12}>rᵢ</text>
 {Array.from({length:n},(_,i)=>{const h=length/n;return <g key={i}><rect x={O.x-11} y={top+i*h} width="22" height={Math.max(1,h-(1-p.continuum)*3)} rx={Math.min(5,h/5)} fill="var(--charge-fill)" stroke="var(--charge)" strokeWidth={p.continuum>.8?.4:.8}/>{n<25&&<text x={O.x-5} y={top+(i+.5)*h+5} style={{fill:'var(--charge)',fontSize:15,fontStyle:'normal'}}>+</text>}</g>})}
 {ghost&&<><rect x={O.x-13} y={2*O.y-ey-8} width="26" height="16" rx="3" fill="none" stroke="var(--charge)" strokeDasharray="3 3" opacity=".5"/><line x1={O.x} y1={2*O.y-ey} x2={px} y2={O.y} stroke="var(--ghost)" strokeDasharray="5 5" opacity=".5"/><text x={O.x-48} y={2*O.y-ey+5}>−y</text></>}
 <g {...handleProps('element')} tabIndex={0} role="slider" aria-label="Representative charge position" aria-valuemin={0} aria-valuemax={1} aria-valuenow={p.element} onKeyDown={ev=>{if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].includes(ev.key)){ev.preventDefault();const delta=['ArrowUp','ArrowRight'].includes(ev.key)?0.05:-0.05;setParams({element:Math.max(0,Math.min(1,p.element+delta))});}}} style={{cursor:'ns-resize',touchAction:'none'}}><rect x={O.x-22} y={ey-17} width="44" height="34" fill="transparent"/><rect className="element-mark" x={O.x-13} y={ey-8} width="26" height="16" rx="4" fill="var(--charge)"/><text x={O.x+22} y={ey+6}>dQ</text></g>
 <text x={O.x-39} y={ey+6}>{alternate?'y′':'y'}</text><text x={O.x-26} y={(alternate?bottom:O.y)+20}>O</text><path d={`M154 ${top}H165M160 ${top}V${bottom}M154 ${bottom}H165`} stroke="var(--ghost)"/><text x="138" y={O.y+5}>L</text><path d={`M${O.x+17} ${O.y+29}H${px-13}`} stroke="var(--ghost)"/><text x={(O.x+px)/2} y={O.y+52}>r</text><text x={O.x+17} y={top-12}>{alternate?'L':'+L/2'}</text><text x={O.x+17} y={bottom+23}>{alternate?'0':'−L/2'}</text>
 {contribution&&<><Arrow x1={px} y1={O.y} x2={px+67} y2={O.y+67*(O.y-ey)/(px-O.x)} color="var(--contribution)"/><text x={px+68} y={O.y+67*(O.y-ey)/(px-O.x)+17} style={{fill:'var(--contribution)'}}>dE</text><Arrow x1={px} y1={O.y} x2={px+67} y2={O.y} color="var(--contribution)"/><Arrow x1={px+67} y1={O.y} x2={px+67} y2={O.y+67*(O.y-ey)/(px-O.x)} color="var(--contribution)" dashed={ghost}/><path d={`M${px+29} ${O.y}A29 29 0 0 1 ${px+29*Math.cos(Math.atan2(O.y-ey,px-O.x))} ${O.y+29*Math.sin(Math.atan2(O.y-ey,px-O.x))}`} fill="none" stroke="var(--contribution)"/><text x={px+35} y={O.y+13}>α</text>{ghost&&<Arrow x1={px} y1={O.y} x2={px+67} y2={O.y-67*(O.y-ey)/(px-O.x)} color="var(--contribution)" dashed/>}</>}
 <Arrow x1={px} y1={O.y} x2={px+netLength} y2={O.y} width={3}/><text x={px+netLength/2} y={O.y-15} style={{fill:'var(--field)'}}>Eₓ</text>
 <g {...handleProps('P')} role="slider" aria-label="Observation distance" aria-valuemin={.5} aria-valuemax={6} aria-valuenow={p.distance} tabIndex={0} onKeyDown={ev=>{if(['ArrowRight','ArrowLeft'].includes(ev.key)){ev.preventDefault();const delta=ev.key==='ArrowRight'?0.1:-0.1;setParams({distance:Math.max(0.5,Math.min(6,p.distance+delta))});}}} style={{cursor:'ew-resize',touchAction:'none'}}><circle cx={px} cy={O.y} r="20" fill="transparent" stroke="var(--foreground)" opacity=".13"/><circle cx={px} cy={O.y} r="7" fill="var(--foreground)"/><text x={px-6} y={O.y-30}>P</text></g>
 {stage===5&&[0,1].map(i=><g key={i} {...handleProps('bound'+i)} role="slider" tabIndex={0} aria-label={i?'Upper bound bracket':'Lower bound bracket'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={boundRange[i]} onKeyDown={ev=>{if(['ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const next:[number,number]=[...boundRange];next[i]=Math.max(0,Math.min(100,next[i]+(ev.key==='ArrowUp'?5:-5)));setBoundRange(next)}}} style={{cursor:'ns-resize',touchAction:'none'}}><rect x={O.x-25} y={bpos(boundRange[i])-14} width="51" height="28" fill="transparent"/><path d={`M${O.x-24} ${bpos(boundRange[i])+(i?10:-10)}v${i?-10:10}h48v${i?10:-10}`} fill="none" stroke="var(--primary)" strokeWidth="3"/><text className="label-small" x={O.x+38} y={bpos(boundRange[i])+4}>{i?'upper':'lower'}</text></g>)}
 <text x="30" y="372" className="label-small">Drag P ↔ · Drag the orange element ↕</text><text x="420" y="372" className="label-small">rᵢ = {pretty(ri)} m</text></svg></div>;
}
